### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by DavidCheas** [FriendsBet/API#1]
Hi,

It seems that the API don't allow cross domains request.

![image](https://cloud.githubusercontent.com/assets/9824855/8778634/4f33d8ee-2eff-11e5-85c2-654d686459e0.png)

Can you fix it?
Thanks,
David

**Comment by YannBertrand** [comment]
Should be fixed by now

**Comment by DavidCheas** [comment]
It works, thank you for the fast answer
